es.index_name: pcawg-r1
es.host: localhost
es.port: 9200
delete_index_if_exists: true  # good for development use

input_dir: input
output_dir: output

indexes:
    "{release_version}-file":
        settings: file.es_settings.yaml


